# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='filiere',
            name='filiere',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='salle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='element',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='year',
            name='annee',
            field=models.CharField(max_length=3),
        ),
    ]
