# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20170503_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Subject')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Group')),
            ],
        ),
        migrations.CreateModel(
            name='TypeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeExam', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='typeExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.TypeExam'),
        ),
    ]
