# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170504_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeElement', models.CharField(max_length=50)),
            ],
        ),
    ]
