# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_typeelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('semaine', models.CharField(max_length=10)),
            ],
        ),
    ]
