# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_filecsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.CharField(max_length=5)),
            ],
        ),
    ]
