# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20170505_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecsv',
            name='semaine',
            field=models.CharField(max_length=10),
        ),
    ]
