# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20170505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecsv',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Semaine'),
        ),
    ]
