# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0014_auto_20170505_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Semaine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
