# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_filecsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='element',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='typeExam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
