# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_freetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='timeslote',
        ),
    ]
