# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_auto_20170508_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaine',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
