# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0024_semaine_date_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenotif', models.DateTimeField()),
                ('message', models.TextField()),
                ('date_delete', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
