# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_subactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactivity',
            name='element',
        ),
        migrations.RemoveField(
            model_name='subactivity',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='subactivity',
            name='semaine',
        ),
        migrations.RemoveField(
            model_name='subactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubActivity',
        ),
    ]
